### ISSUE TITLE
Basic Movement of Character

### ISSUE THREAD

**Issue by lordexishigh** [30005209/SummerProject#1]
A basic movement for our character to start with, doesnt need to be too fancy for now, just to work

**Comment by nimshi89** [comment]
I can have a go at it :)

**Comment by nimshi89** [comment]
Hey Guys. 

So I am unable to push to the repo :( 

![image](https://user-images.githubusercontent.com/43893201/119183461-09e26b80-ba6c-11eb-8016-19097e2dc94f.png)

**Comment by lordexishigh** [comment]
Ive never had this issue ;/. I can have a look at it once am home

**Comment by nimshi89** [comment]
Thanks mate :) I think that Isaac will have to set permission for me. :D

**Comment by scrab333** [comment]
perhaps, am gonna see if i'll get the same error

**Comment by nimshi89** [comment]
Okay ;)

**Comment by scrab333** [comment]
yup, it's same for me, i get a message that i don't have access to SumerProject

**Comment by nimshi89** [comment]
I feel discriminated XD I am not good enough for the repo XD

**Comment by lordexishigh** [comment]
I will do the jumping as i need it to do the double jump action

**Comment by 30005209** [comment]
jonesyirg@gmail.com

**Comment by IJCoding** [comment]
Due to being abandoned this issue is being closed.
