### ISSUE TITLE
Basic UI

### ISSUE THREAD

**Issue by lordexishigh** [30005209/SummerProject#11]
Adding main menu, pause menu and win screen for a start should be enough for a basic start

**Comment by IJCoding** [comment]
https://www.youtube.com/watch?v=HwdweCX5aMI

Been using this video as a reference point

**Comment by IJCoding** [comment]
![image](https://user-images.githubusercontent.com/55790193/119265777-d1639e80-bbdf-11eb-9efc-7ca2aa274f8d.png)

Basic Main Menu sorted

**Comment by IJCoding** [comment]
![image](https://user-images.githubusercontent.com/55790193/119576863-741f4700-bdb1-11eb-8034-5316dda90d2e.png)

Blocked off major areas (images (the colour) are just placeholder)

**Comment by IJCoding** [comment]
To add more areas can just add a new element :)

**Comment by IJCoding** [comment]
I believe it is all working now (following some issues raised on the discord) - will confirm prior to closing this.
