### ISSUE TITLE
Basic Movement - Portable

### ISSUE THREAD

**Issue by IJCoding** [30005209/SummerProject#18]
Implement a portable movement script that both the players and enemies can use

**Comment by nimshi89** [comment]
![image](https://user-images.githubusercontent.com/43893201/120493244-b13b9880-c3b2-11eb-9d7b-0c11ab610baa.png)

SO I am having this issue when I try to add the scrip[t to the enemy. 

which looks like this and I can't see any fu*king difference with the TargetPlayer script.
![image](https://user-images.githubusercontent.com/43893201/120493409-d7613880-c3b2-11eb-9308-a89ff6f083a2.png)
any advice?

**Comment by nimshi89** [comment]
I know some of the comments are of:/ this would be a prototype and so far can't add it to anything to see how it works

**Comment by lordexishigh** [comment]
Shouldnt the class have the same name as the script's name. So 
public class NewBehaviourClass : MonoBehaviour would be
public class CheckForTarget : MonoBehaviour 
Not sure if am right, but still have a go at it

**Comment by nimshi89** [comment]
Damn XD yeah Ill give that a go :D

**Comment by nimshi89** [comment]
![image](https://user-images.githubusercontent.com/43893201/120496854-d4b41280-c3b5-11eb-8f38-91ba5d2f5900.png)
It is working YALL :D
there you can set the tag that the Gamecomponent has and that will be the target :D

**Comment by lordexishigh** [comment]
Awesome

**Comment by nimshi89** [comment]
Okay so Inheritance :D how is it with Unity? 

![image](https://user-images.githubusercontent.com/43893201/120499961-645ac080-c3b8-11eb-8afb-09a3b1258bb7.png)


I made a main class that has 

![image](https://user-images.githubusercontent.com/43893201/120500059-76d4fa00-c3b8-11eb-8318-48381abfd338.png)

**Comment by IJCoding** [comment]
Would you like me to make the base class script from which you can inherit :)

**Comment by IJCoding** [comment]
![image](https://user-images.githubusercontent.com/55790193/120530803-d1c91a00-c3d5-11eb-85eb-7b88de68e69a.png)

Added a behaviour controller which contains places for attack / movement scripts

**Comment by IJCoding** [comment]
![image](https://user-images.githubusercontent.com/55790193/120530893-e73e4400-c3d5-11eb-8c74-4f645797a449.png)

Added a Player movement script (essentially the one that @nimshi89  made) but made it inherit from a generic Movement Script

**Comment by IJCoding** [comment]
![image](https://user-images.githubusercontent.com/55790193/120530977-0046f500-c3d6-11eb-8041-f4e0ff3467c1.png)

Did the same for the Mole version of movement

**Comment by IJCoding** [comment]
Due to being abandoned this issue is being closed.
