### ISSUE TITLE
Basic level design 

### ISSUE THREAD

**Issue by lordexishigh** [30005209/SummerProject#2]
Create at-least a single level that we can use to test the game on and give an idea on how the game will look like. Once that is done, we can discuss on if we like the level's aesthetic/looks and if so can continue populating levels

**Comment by IJCoding** [comment]
https://www.youtube.com/watch?v=ryISV_nH8qw

found this video for tilemaps - will take a look tomorrow :)

**Comment by IJCoding** [comment]
https://assetstore.unity.com/packages/2d/textures-materials/tiles/2d-metroidvania-tileset-16x16-131908

Bought this asset pack as I think it would be fine - at least for prototyping :)

**Comment by IJCoding** [comment]
![image](https://user-images.githubusercontent.com/55790193/120116696-49ead200-c181-11eb-923a-af9b0881925f.png)

This is required to do the 2D terrain tilemaps

**Comment by IJCoding** [comment]
![image](https://user-images.githubusercontent.com/55790193/120116819-db5a4400-c181-11eb-870a-7a037fb9717d.png)
Also requires this

**Comment by IJCoding** [comment]
![image](https://user-images.githubusercontent.com/55790193/120117426-1447e800-c185-11eb-8c5a-d322f1ee77f0.png)

Due to being pixel based - hard edges - anti-aliasing would blur edges which is not what we'd want

**Comment by IJCoding** [comment]
![image](https://user-images.githubusercontent.com/55790193/120117564-a6e88700-c185-11eb-9d62-6382484a47f0.png)

Basic map making can be done - will make rule based tiling system now / post-meeting
