### ISSUE TITLE
Basic monster AI

### ISSUE THREAD

**Issue by lordexishigh** [30005209/SummerProject#4]
Create the AI for the monster. For now, the monster should just follow the player's movement

**Comment by nimshi89** [comment]
I'll try my best :D

**Comment by scrab333** [comment]
Let me know if you have any problems or need any help. i wouldn't mind giving this a go

**Comment by nimshi89** [comment]
We could try and implement something together :)

**Comment by nimshi89** [comment]
Enemy can now follow the player :D

**Comment by IJCoding** [comment]
nice work on the mole - follows well :)

**Comment by IJCoding** [comment]
Due to being abandoned this issue is being closed.
