### ISSUE TITLE
Basic Insanity 

### ISSUE THREAD

**Issue by lordexishigh** [30005209/SummerProject#6]
A basic insanity that we will use to in further stages of the game to create the illusion effects we discussed. I can work on this

**Comment by lordexishigh** [comment]
I've implemented the insanity, but for now there is no way to interact with it yet as we havent decided on how the insanity will work exactly

**Comment by nimshi89** [comment]
Awesome :)

**Comment by IJCoding** [comment]
![image](https://user-images.githubusercontent.com/55790193/119576751-433f1200-bdb1-11eb-818e-f772aaa38b89.png)

@lordexishigh  - so I've been tinkering whilst doing the UI (In an attempt to scale) and cant find a way to do it without scaling. Is there a way to do this another way :)

Your way works but only when small :)

**Comment by scrab333** [comment]
maybe if we would to re-do the imagine in a pixel art format it would look better?

**Comment by IJCoding** [comment]
Due to being abandoned this issue is being closed.
